# Generated by Django 4.1.3 on 2022-12-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "restaurant",
            "0004_alter_cook_options_alter_cook_years_of_experience_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="years_of_experience",
            field=models.IntegerField(default=1),
        ),
    ]
